///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class CategoryResponseDataLinks {
/*
{
  "first": "https://inventory.grozaarbd.com/api/v1/user/get-parent-categories?page=1",
  "last": "https://inventory.grozaarbd.com/api/v1/user/get-parent-categories?page=1",
  "prev": null,
  "next": null
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;

  CategoryResponseDataLinks({
    this.first,
    this.last,
    this.prev,
    this.next,
  });
  CategoryResponseDataLinks.fromJson(Map<String, dynamic> json) {
    first = json['first']?.toString();
    last = json['last']?.toString();
    prev = json['prev']?.toString();
    next = json['next']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first'] = first;
    data['last'] = last;
    data['prev'] = prev;
    data['next'] = next;
    return data;
  }
}

class CategoryResponseDataMeta {
/*
{
  "current_page": 1,
  "from": 1,
  "last_page": 1,
  "per_page": 20,
  "to": 20,
  "total": 20
}
*/

  String? currentPage;
  String? from;
  String? lastPage;
  String? perPage;
  String? to;
  String? total;

  CategoryResponseDataMeta({
    this.currentPage,
    this.from,
    this.lastPage,
    this.perPage,
    this.to,
    this.total,
  });
  CategoryResponseDataMeta.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toString();
    from = json['from']?.toString();
    lastPage = json['last_page']?.toString();
    perPage = json['per_page']?.toString();
    to = json['to']?.toString();
    total = json['total']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['per_page'] = perPage;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class CategoryResponseDataData {
/*
{
  "id": 12,
  "name": "Cooking",
  "image": "categories/1748768433_578382895_1.webp",
  "image_url": "https://inventory.grozaarbd.com/storage/categories/1748768433_578382895_1.webp"
}
*/

  String? id;
  String? name;
  String? image;
  String? imageUrl;

  CategoryResponseDataData({
    this.id,
    this.name,
    this.image,
    this.imageUrl,
  });
  CategoryResponseDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    imageUrl = json['image_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['image_url'] = imageUrl;
    return data;
  }
}

class CategoryResponseData {
/*
{
  "data": [
    {
      "id": 12,
      "name": "Cooking",
      "image": "categories/1748768433_578382895_1.webp",
      "image_url": "https://inventory.grozaarbd.com/storage/categories/1748768433_578382895_1.webp"
    }
  ],
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 1,
    "per_page": 20,
    "to": 20,
    "total": 20
  },
  "links": {
    "first": "https://inventory.grozaarbd.com/api/v1/user/get-parent-categories?page=1",
    "last": "https://inventory.grozaarbd.com/api/v1/user/get-parent-categories?page=1",
    "prev": null,
    "next": null
  }
}
*/

  List<CategoryResponseDataData?>? data;
  CategoryResponseDataMeta? meta;
  CategoryResponseDataLinks? links;

  CategoryResponseData({
    this.data,
    this.meta,
    this.links,
  });
  CategoryResponseData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <CategoryResponseDataData>[];
      v.forEach((v) {
        arr0.add(CategoryResponseDataData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null && (json['meta'] is Map)) ? CategoryResponseDataMeta.fromJson(json['meta']) : null;
    links = (json['links'] != null && (json['links'] is Map)) ? CategoryResponseDataLinks.fromJson(json['links']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}

class CategoryResponse {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "data": [
      {
        "id": 12,
        "name": "Cooking",
        "image": "categories/1748768433_578382895_1.webp",
        "image_url": "https://inventory.grozaarbd.com/storage/categories/1748768433_578382895_1.webp"
      }
    ],
    "meta": {
      "current_page": 1,
      "from": 1,
      "last_page": 1,
      "per_page": 20,
      "to": 20,
      "total": 20
    },
    "links": {
      "first": "https://inventory.grozaarbd.com/api/v1/user/get-parent-categories?page=1",
      "last": "https://inventory.grozaarbd.com/api/v1/user/get-parent-categories?page=1",
      "prev": null,
      "next": null
    }
  }
}
*/

  bool? success;
  String? message;
  CategoryResponseData? data;

  CategoryResponse({
    this.success,
    this.message,
    this.data,
  });
  CategoryResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null && (json['data'] is Map)) ? CategoryResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
