///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class NewArrivalResponseDataDataLinks {
/*
{
  "first": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=1",
  "last": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=5",
  "prev": null,
  "next": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=2"
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;

  NewArrivalResponseDataDataLinks({
    this.first,
    this.last,
    this.prev,
    this.next,
  });
  NewArrivalResponseDataDataLinks.fromJson(Map<String, dynamic> json) {
    first = json['first']?.toString();
    last = json['last']?.toString();
    prev = json['prev']?.toString();
    next = json['next']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first'] = first;
    data['last'] = last;
    data['prev'] = prev;
    data['next'] = next;
    return data;
  }
}

class NewArrivalResponseDataDataMeta {
/*
{
  "current_page": 1,
  "from": 1,
  "last_page": 5,
  "per_page": 10,
  "to": 10,
  "total": 44
}
*/

  String? currentPage;
  String? from;
  String? lastPage;
  String? perPage;
  String? to;
  String? total;

  NewArrivalResponseDataDataMeta({
    this.currentPage,
    this.from,
    this.lastPage,
    this.perPage,
    this.to,
    this.total,
  });
  NewArrivalResponseDataDataMeta.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toString();
    from = json['from']?.toString();
    lastPage = json['last_page']?.toString();
    perPage = json['per_page']?.toString();
    to = json['to']?.toString();
    total = json['total']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['per_page'] = perPage;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class NewArrivalResponseDataDataDataRating {
/*
{
  "averageRating": "0",
  "totalReviewCount": 0
}
*/

  String? averageRating;
  String? totalReviewCount;

  NewArrivalResponseDataDataDataRating({
    this.averageRating,
    this.totalReviewCount,
  });
  NewArrivalResponseDataDataDataRating.fromJson(Map<String, dynamic> json) {
    averageRating = json['averageRating']?.toString();
    totalReviewCount = json['totalReviewCount']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['averageRating'] = averageRating;
    data['totalReviewCount'] = totalReviewCount;
    return data;
  }
}

class NewArrivalResponseDataDataData {
/*
{
  "id": 43,
  "price": "৳ 320",
  "tax_price": null,
  "promotion_price": null,
  "sub_total": "৳ 320",
  "image_url": "https://inventory.grozaarbd.com/storage/products/1750408983_1169808145_1.jpg",
  "name": "Pasta",
  "total_stock_quantity": 99,
  "rating": {
    "averageRating": "0",
    "totalReviewCount": 0
  },
  "promotion_text": "",
  "old_price": ""
}
*/

  String? id;
  String? price;
  String? taxPrice;
  String? promotionPrice;
  String? subTotal;
  String? imageUrl;
  String? name;
  String? totalStockQuantity;
  NewArrivalResponseDataDataDataRating? rating;
  String? promotionText;
  String? oldPrice;

  NewArrivalResponseDataDataData({
    this.id,
    this.price,
    this.taxPrice,
    this.promotionPrice,
    this.subTotal,
    this.imageUrl,
    this.name,
    this.totalStockQuantity,
    this.rating,
    this.promotionText,
    this.oldPrice,
  });
  NewArrivalResponseDataDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    price = json['price']?.toString();
    taxPrice = json['tax_price']?.toString();
    promotionPrice = json['promotion_price']?.toString();
    subTotal = json['sub_total']?.toString();
    imageUrl = json['image_url']?.toString();
    name = json['name']?.toString();
    totalStockQuantity = json['total_stock_quantity']?.toString();
    rating = (json['rating'] != null) ? NewArrivalResponseDataDataDataRating.fromJson(json['rating']) : null;
    promotionText = json['promotion_text']?.toString();
    oldPrice = json['old_price']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['price'] = price;
    data['tax_price'] = taxPrice;
    data['promotion_price'] = promotionPrice;
    data['sub_total'] = subTotal;
    data['image_url'] = imageUrl;
    data['name'] = name;
    data['total_stock_quantity'] = totalStockQuantity;
    if (rating != null) {
      data['rating'] = rating!.toJson();
    }
    data['promotion_text'] = promotionText;
    data['old_price'] = oldPrice;
    return data;
  }
}

class NewArrivalResponseDataData {
/*
{
  "data": [
    {
      "id": 43,
      "price": "৳ 320",
      "tax_price": null,
      "promotion_price": null,
      "sub_total": "৳ 320",
      "image_url": "https://inventory.grozaarbd.com/storage/products/1750408983_1169808145_1.jpg",
      "name": "Pasta",
      "total_stock_quantity": 99,
      "rating": {
        "averageRating": "0",
        "totalReviewCount": 0
      },
      "promotion_text": "",
      "old_price": ""
    }
  ],
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 5,
    "per_page": 10,
    "to": 10,
    "total": 44
  },
  "links": {
    "first": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=1",
    "last": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=5",
    "prev": null,
    "next": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=2"
  }
}
*/

  List<NewArrivalResponseDataDataData?>? data;
  NewArrivalResponseDataDataMeta? meta;
  NewArrivalResponseDataDataLinks? links;

  NewArrivalResponseDataData({
    this.data,
    this.meta,
    this.links,
  });
  NewArrivalResponseDataData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NewArrivalResponseDataDataData>[];
      v.forEach((v) {
        arr0.add(NewArrivalResponseDataDataData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? NewArrivalResponseDataDataMeta.fromJson(json['meta']) : null;
    links = (json['links'] != null) ? NewArrivalResponseDataDataLinks.fromJson(json['links']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}

class NewArrivalResponseData {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "data": [
      {
        "id": 43,
        "price": "৳ 320",
        "tax_price": null,
        "promotion_price": null,
        "sub_total": "৳ 320",
        "image_url": "https://inventory.grozaarbd.com/storage/products/1750408983_1169808145_1.jpg",
        "name": "Pasta",
        "total_stock_quantity": 99,
        "rating": {
          "averageRating": "0",
          "totalReviewCount": 0
        },
        "promotion_text": "",
        "old_price": ""
      }
    ],
    "meta": {
      "current_page": 1,
      "from": 1,
      "last_page": 5,
      "per_page": 10,
      "to": 10,
      "total": 44
    },
    "links": {
      "first": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=1",
      "last": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=5",
      "prev": null,
      "next": "https://inventory.grozaarbd.com/api/v1/user/new-arrival-products?page=2"
    }
  }
}
*/

  bool? success;
  String? message;
  NewArrivalResponseDataData? data;

  NewArrivalResponseData({
    this.success,
    this.message,
    this.data,
  });
  NewArrivalResponseData.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? NewArrivalResponseDataData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
