///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class OrderHistoryResponseDataLinks {
  /*
{
  "first": "https://inventory.grozaarbd.com/api/v1/user/ongoing-orders?page=1",
  "last": "https://inventory.grozaarbd.com/api/v1/user/ongoing-orders?page=1",
  "prev": null,
  "next": null
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;

  OrderHistoryResponseDataLinks({this.first, this.last, this.prev, this.next});

  OrderHistoryResponseDataLinks.fromJson(Map<String, dynamic> json) {
    first = json['first']?.toString();
    last = json['last']?.toString();
    prev = json['prev']?.toString();
    next = json['next']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first'] = first;
    data['last'] = last;
    data['prev'] = prev;
    data['next'] = next;
    return data;
  }
}

class OrderHistoryResponseDataMeta {
  /*
{
  "current_page": 1,
  "from": 1,
  "last_page": 1,
  "per_page": 50,
  "to": 2,
  "total": 2
}
*/

  String? currentPage;
  String? from;
  String? lastPage;
  String? perPage;
  String? to;
  String? total;

  OrderHistoryResponseDataMeta({
    this.currentPage,
    this.from,
    this.lastPage,
    this.perPage,
    this.to,
    this.total,
  });

  OrderHistoryResponseDataMeta.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toString();
    from = json['from']?.toString();
    lastPage = json['last_page']?.toString();
    perPage = json['per_page']?.toString();
    to = json['to']?.toString();
    total = json['total']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['per_page'] = perPage;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class OrderHistoryResponseDataData {
  /*
{
  "id": 9,
  "invoice_no": "INV-2987-0008",
  "date": "2025-05-25 14:18:50",
  "time": "17 hours ago",
  "price": "71.33",
  "status": "pending"
}
*/

  String? id;
  String? invoiceNo;
  String? date;
  String? time;
  String? price;
  String? status;

  OrderHistoryResponseDataData({
    this.id,
    this.invoiceNo,
    this.date,
    this.time,
    this.price,
    this.status,
  });

  OrderHistoryResponseDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    invoiceNo = json['invoice_no']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
    price = json['price']?.toString();
    status = json['status']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['invoice_no'] = invoiceNo;
    data['date'] = date;
    data['time'] = time;
    data['price'] = price;
    data['status'] = status;
    return data;
  }
}

class OrderHistoryResponseData {
  /*
{
  "data": [
    {
      "id": 9,
      "invoice_no": "INV-2987-0008",
      "date": "2025-05-25 14:18:50",
      "time": "17 hours ago",
      "price": "71.33",
      "status": "pending"
    }
  ],
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 1,
    "per_page": 50,
    "to": 2,
    "total": 2
  },
  "links": {
    "first": "https://inventory.grozaarbd.com/api/v1/user/ongoing-orders?page=1",
    "last": "https://inventory.grozaarbd.com/api/v1/user/ongoing-orders?page=1",
    "prev": null,
    "next": null
  }
}
*/

  List<OrderHistoryResponseDataData?>? data;
  OrderHistoryResponseDataMeta? meta;
  OrderHistoryResponseDataLinks? links;

  OrderHistoryResponseData({this.data, this.meta, this.links});

  OrderHistoryResponseData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <OrderHistoryResponseDataData>[];
      v.forEach((v) {
        arr0.add(OrderHistoryResponseDataData.fromJson(v));
      });
      this.data = arr0;
    }
    meta =
        (json['meta'] != null && (json['meta'] is Map))
            ? OrderHistoryResponseDataMeta.fromJson(json['meta'])
            : null;
    links =
        (json['links'] != null && (json['links'] is Map))
            ? OrderHistoryResponseDataLinks.fromJson(json['links'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}

class OrderHistoryResponse {
  /*
{
  "success": true,
  "message": "Success",
  "data": {
    "data": [
      {
        "id": 9,
        "invoice_no": "INV-2987-0008",
        "date": "2025-05-25 14:18:50",
        "time": "17 hours ago",
        "price": "71.33",
        "status": "pending"
      }
    ],
    "meta": {
      "current_page": 1,
      "from": 1,
      "last_page": 1,
      "per_page": 50,
      "to": 2,
      "total": 2
    },
    "links": {
      "first": "https://inventory.grozaarbd.com/api/v1/user/ongoing-orders?page=1",
      "last": "https://inventory.grozaarbd.com/api/v1/user/ongoing-orders?page=1",
      "prev": null,
      "next": null
    }
  }
}
*/

  bool? success;
  String? message;
  OrderHistoryResponseData? data;

  OrderHistoryResponse({this.success, this.message, this.data});

  OrderHistoryResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data =
        (json['data'] != null && (json['data'] is Map))
            ? OrderHistoryResponseData.fromJson(json['data'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
