///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductDetailsResponseDataRelatedItemsLinks {
  /*
{
  "first": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
  "last": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
  "prev": null,
  "next": null
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;

  ProductDetailsResponseDataRelatedItemsLinks({
    this.first,
    this.last,
    this.prev,
    this.next,
  });

  ProductDetailsResponseDataRelatedItemsLinks.fromJson(
    Map<String, dynamic> json,
  ) {
    first = json['first']?.toString();
    last = json['last']?.toString();
    prev = json['prev']?.toString();
    next = json['next']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first'] = first;
    data['last'] = last;
    data['prev'] = prev;
    data['next'] = next;
    return data;
  }
}

class ProductDetailsResponseDataRelatedItemsMeta {
  /*
{
  "current_page": 1,
  "from": 1,
  "last_page": 1,
  "per_page": 20,
  "to": 1,
  "total": 1
}
*/

  String? currentPage;
  String? from;
  String? lastPage;
  String? perPage;
  String? to;
  String? total;

  ProductDetailsResponseDataRelatedItemsMeta({
    this.currentPage,
    this.from,
    this.lastPage,
    this.perPage,
    this.to,
    this.total,
  });

  ProductDetailsResponseDataRelatedItemsMeta.fromJson(
    Map<String, dynamic> json,
  ) {
    currentPage = json['current_page']?.toString();
    from = json['from']?.toString();
    lastPage = json['last_page']?.toString();
    perPage = json['per_page']?.toString();
    to = json['to']?.toString();
    total = json['total']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['per_page'] = perPage;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class ProductDetailsResponseDataRelatedItemsDataRating {
  /*
{
  "averageRating": "0",
  "totalReviewCount": 0
}
*/

  String? averageRating;
  String? totalReviewCount;

  ProductDetailsResponseDataRelatedItemsDataRating({
    this.averageRating,
    this.totalReviewCount,
  });

  ProductDetailsResponseDataRelatedItemsDataRating.fromJson(
    Map<String, dynamic> json,
  ) {
    averageRating = json['averageRating']?.toString();
    totalReviewCount = json['totalReviewCount']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['averageRating'] = averageRating;
    data['totalReviewCount'] = totalReviewCount;
    return data;
  }
}

class ProductDetailsResponseDataRelatedItemsDataTaxes {
  /*
{
  "has_tax": "1",
  "tax_amount": "1"
}
*/

  String? hasTax;
  String? taxAmount;

  ProductDetailsResponseDataRelatedItemsDataTaxes({
    this.hasTax,
    this.taxAmount,
  });

  ProductDetailsResponseDataRelatedItemsDataTaxes.fromJson(
    Map<String, dynamic> json,
  ) {
    hasTax = json['has_tax']?.toString();
    taxAmount = json['tax_amount']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['has_tax'] = hasTax;
    data['tax_amount'] = taxAmount;
    return data;
  }
}

class ProductDetailsResponseDataRelatedItemsData {
  /*
{
  "id": 2,
  "price": "22.95",
  "image": "products/1745483961_598300393_1.jpg",
  "image_url": "https://grozaar.heizoelscout.com/storage/products/1745483961_598300393_1.jpg",
  "name": "customer product",
  "barcode_image_url": "https://grozaar.heizoelscout.com/storage",
  "total_stock_quantity": 990,
  "taxes": {
    "has_tax": "1",
    "tax_amount": "1"
  },
  "rating": {
    "averageRating": "0",
    "totalReviewCount": 0
  }
}
*/

  String? id;
  String? price;
  String? image;
  String? imageUrl;
  String? name;
  String? barcodeImageUrl;
  String? totalStockQuantity;
  ProductDetailsResponseDataRelatedItemsDataTaxes? taxes;
  ProductDetailsResponseDataRelatedItemsDataRating? rating;

  ProductDetailsResponseDataRelatedItemsData({
    this.id,
    this.price,
    this.image,
    this.imageUrl,
    this.name,
    this.barcodeImageUrl,
    this.totalStockQuantity,
    this.taxes,
    this.rating,
  });

  ProductDetailsResponseDataRelatedItemsData.fromJson(
    Map<String, dynamic> json,
  ) {
    id = json['id']?.toString();
    price = json['price']?.toString();
    image = json['image']?.toString();
    imageUrl = json['image_url']?.toString();
    name = json['name']?.toString();
    barcodeImageUrl = json['barcode_image_url']?.toString();
    totalStockQuantity = json['total_stock_quantity']?.toString();
    taxes =
        (json['taxes'] != null && (json['taxes'] is Map))
            ? ProductDetailsResponseDataRelatedItemsDataTaxes.fromJson(
              json['taxes'],
            )
            : null;
    rating =
        (json['rating'] != null && (json['rating'] is Map))
            ? ProductDetailsResponseDataRelatedItemsDataRating.fromJson(
              json['rating'],
            )
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['price'] = price;
    data['image'] = image;
    data['image_url'] = imageUrl;
    data['name'] = name;
    data['barcode_image_url'] = barcodeImageUrl;
    data['total_stock_quantity'] = totalStockQuantity;
    if (taxes != null) {
      data['taxes'] = taxes!.toJson();
    }
    if (rating != null) {
      data['rating'] = rating!.toJson();
    }
    return data;
  }
}

class ProductDetailsResponseDataRelatedItems {
  /*
{
  "data": [
    {
      "id": 2,
      "price": "22.95",
      "image": "products/1745483961_598300393_1.jpg",
      "image_url": "https://grozaar.heizoelscout.com/storage/products/1745483961_598300393_1.jpg",
      "name": "customer product",
      "barcode_image_url": "https://grozaar.heizoelscout.com/storage",
      "total_stock_quantity": 990,
      "taxes": {
        "has_tax": "1",
        "tax_amount": "1"
      },
      "rating": {
        "averageRating": "0",
        "totalReviewCount": 0
      }
    }
  ],
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 1,
    "per_page": 20,
    "to": 1,
    "total": 1
  },
  "links": {
    "first": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
    "last": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
    "prev": null,
    "next": null
  }
}
*/

  List<ProductDetailsResponseDataRelatedItemsData?>? data;
  ProductDetailsResponseDataRelatedItemsMeta? meta;
  ProductDetailsResponseDataRelatedItemsLinks? links;

  ProductDetailsResponseDataRelatedItems({this.data, this.meta, this.links});

  ProductDetailsResponseDataRelatedItems.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <ProductDetailsResponseDataRelatedItemsData>[];
      v.forEach((v) {
        arr0.add(ProductDetailsResponseDataRelatedItemsData.fromJson(v));
      });
      this.data = arr0;
    }
    meta =
        (json['meta'] != null && (json['meta'] is Map))
            ? ProductDetailsResponseDataRelatedItemsMeta.fromJson(json['meta'])
            : null;
    links =
        (json['links'] != null && (json['links'] is Map))
            ? ProductDetailsResponseDataRelatedItemsLinks.fromJson(
              json['links'],
            )
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}

class ProductDetailsResponseDataProductBrand {
  /*
{
  "id": 1,
  "name": "Walmart"
}
*/

  String? id;
  String? name;

  ProductDetailsResponseDataProductBrand({this.id, this.name});

  ProductDetailsResponseDataProductBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ProductDetailsResponseDataProductCategory {
  /*
{
  "id": 1,
  "name": "Fruits & Vegetables"
}
*/

  String? id;
  String? name;

  ProductDetailsResponseDataProductCategory({this.id, this.name});

  ProductDetailsResponseDataProductCategory.fromJson(
    Map<String, dynamic> json,
  ) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ProductDetailsResponseDataProductProductUnit {
  /*
{
  "id": 1,
  "name": "Ps",
  "symbol": "ps",
  "type": "quantity"
}
*/

  String? id;
  String? name;
  String? symbol;
  String? type;

  ProductDetailsResponseDataProductProductUnit({
    this.id,
    this.name,
    this.symbol,
    this.type,
  });

  ProductDetailsResponseDataProductProductUnit.fromJson(
    Map<String, dynamic> json,
  ) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    symbol = json['symbol']?.toString();
    type = json['type']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['symbol'] = symbol;
    data['type'] = type;
    return data;
  }
}

class ProductDetailsResponseDataProductRating {
  /*
{
  "averageRating": "1.5",
  "totalReviewCount": 1
}
*/

  String? averageRating;
  String? totalReviewCount;

  ProductDetailsResponseDataProductRating({
    this.averageRating,
    this.totalReviewCount,
  });

  ProductDetailsResponseDataProductRating.fromJson(Map<String, dynamic> json) {
    averageRating = json['averageRating']?.toString();
    totalReviewCount = json['totalReviewCount']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['averageRating'] = averageRating;
    data['totalReviewCount'] = totalReviewCount;
    return data;
  }
}

class ProductDetailsResponseDataProductTaxes {
  /*
{
  "has_tax": "1",
  "tax_amount": "2"
}
*/

  String? hasTax;
  String? taxAmount;

  ProductDetailsResponseDataProductTaxes({this.hasTax, this.taxAmount});

  ProductDetailsResponseDataProductTaxes.fromJson(Map<String, dynamic> json) {
    hasTax = json['has_tax']?.toString();
    taxAmount = json['tax_amount']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['has_tax'] = hasTax;
    data['tax_amount'] = taxAmount;
    return data;
  }
}

class ProductDetailsResponseDataProduct {
  /*
{
  "id": 1,
  "name": "Both Product",
  "image_url": "https://grozaar.heizoelscout.com/storage/products/1745483907_841631781_1.jpeg",
  "price": "20.91",
  "taxes": {
    "has_tax": "1",
    "tax_amount": "2"
  },
  "rating": {
    "averageRating": "1.5",
    "totalReviewCount": 1
  },
  "total_stock_quantity": 1987,
  "product_unit": {
    "id": 1,
    "name": "Ps",
    "symbol": "ps",
    "type": "quantity"
  },
  "notes": "",
  "latest_promotion_item": null,
  "category": {
    "id": 1,
    "name": "Fruits & Vegetables"
  },
  "brand": {
    "id": 1,
    "name": "Walmart"
  }
}
*/

  String? id;
  String? name;
  String? imageUrl;
  String? price;
  ProductDetailsResponseDataProductTaxes? taxes;
  ProductDetailsResponseDataProductRating? rating;
  String? totalStockQuantity;
  ProductDetailsResponseDataProductProductUnit? productUnit;
  String? notes;
  String? latestPromotionItem;
  ProductDetailsResponseDataProductCategory? category;
  ProductDetailsResponseDataProductBrand? brand;

  ProductDetailsResponseDataProduct({
    this.id,
    this.name,
    this.imageUrl,
    this.price,
    this.taxes,
    this.rating,
    this.totalStockQuantity,
    this.productUnit,
    this.notes,
    this.latestPromotionItem,
    this.category,
    this.brand,
  });

  ProductDetailsResponseDataProduct.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    imageUrl = json['image_url']?.toString();
    price = json['price']?.toString();
    taxes =
        (json['taxes'] != null && (json['taxes'] is Map))
            ? ProductDetailsResponseDataProductTaxes.fromJson(json['taxes'])
            : null;
    rating =
        (json['rating'] != null && (json['rating'] is Map))
            ? ProductDetailsResponseDataProductRating.fromJson(json['rating'])
            : null;
    totalStockQuantity = json['total_stock_quantity']?.toString();
    productUnit =
        (json['product_unit'] != null && (json['product_unit'] is Map))
            ? ProductDetailsResponseDataProductProductUnit.fromJson(
              json['product_unit'],
            )
            : null;
    notes = json['notes']?.toString();
    latestPromotionItem = json['latest_promotion_item']?.toString();
    category =
        (json['category'] != null && (json['category'] is Map))
            ? ProductDetailsResponseDataProductCategory.fromJson(
              json['category'],
            )
            : null;
    brand =
        (json['brand'] != null && (json['brand'] is Map))
            ? ProductDetailsResponseDataProductBrand.fromJson(json['brand'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image_url'] = imageUrl;
    data['price'] = price;
    if (taxes != null) {
      data['taxes'] = taxes!.toJson();
    }
    if (rating != null) {
      data['rating'] = rating!.toJson();
    }
    data['total_stock_quantity'] = totalStockQuantity;
    if (productUnit != null) {
      data['product_unit'] = productUnit!.toJson();
    }
    data['notes'] = notes;
    data['latest_promotion_item'] = latestPromotionItem;
    if (category != null) {
      data['category'] = category!.toJson();
    }
    if (brand != null) {
      data['brand'] = brand!.toJson();
    }
    return data;
  }
}

class ProductDetailsResponseData {
  /*
{
  "product": {
    "id": 1,
    "name": "Both Product",
    "image_url": "https://grozaar.heizoelscout.com/storage/products/1745483907_841631781_1.jpeg",
    "price": "20.91",
    "taxes": {
      "has_tax": "1",
      "tax_amount": "2"
    },
    "rating": {
      "averageRating": "1.5",
      "totalReviewCount": 1
    },
    "total_stock_quantity": 1987,
    "product_unit": {
      "id": 1,
      "name": "Ps",
      "symbol": "ps",
      "type": "quantity"
    },
    "notes": "",
    "latest_promotion_item": null,
    "category": {
      "id": 1,
      "name": "Fruits & Vegetables"
    },
    "brand": {
      "id": 1,
      "name": "Walmart"
    }
  },
  "related_items": {
    "data": [
      {
        "id": 2,
        "price": "22.95",
        "image": "products/1745483961_598300393_1.jpg",
        "image_url": "https://grozaar.heizoelscout.com/storage/products/1745483961_598300393_1.jpg",
        "name": "customer product",
        "barcode_image_url": "https://grozaar.heizoelscout.com/storage",
        "total_stock_quantity": 990,
        "taxes": {
          "has_tax": "1",
          "tax_amount": "1"
        },
        "rating": {
          "averageRating": "0",
          "totalReviewCount": 0
        }
      }
    ],
    "meta": {
      "current_page": 1,
      "from": 1,
      "last_page": 1,
      "per_page": 20,
      "to": 1,
      "total": 1
    },
    "links": {
      "first": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
      "last": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
      "prev": null,
      "next": null
    }
  }
}
*/

  ProductDetailsResponseDataProduct? product;
  ProductDetailsResponseDataRelatedItems? relatedItems;

  ProductDetailsResponseData({this.product, this.relatedItems});

  ProductDetailsResponseData.fromJson(Map<String, dynamic> json) {
    product =
        (json['product'] != null && (json['product'] is Map))
            ? ProductDetailsResponseDataProduct.fromJson(json['product'])
            : null;
    relatedItems =
        (json['related_items'] != null && (json['related_items'] is Map))
            ? ProductDetailsResponseDataRelatedItems.fromJson(
              json['related_items'],
            )
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (product != null) {
      data['product'] = product!.toJson();
    }
    if (relatedItems != null) {
      data['related_items'] = relatedItems!.toJson();
    }
    return data;
  }
}

class ProductDetailsResponse {
  /*
{
  "success": true,
  "message": "Product details loaded successfully",
  "data": {
    "product": {
      "id": 1,
      "name": "Both Product",
      "image_url": "https://grozaar.heizoelscout.com/storage/products/1745483907_841631781_1.jpeg",
      "price": "20.91",
      "taxes": {
        "has_tax": "1",
        "tax_amount": "2"
      },
      "rating": {
        "averageRating": "1.5",
        "totalReviewCount": 1
      },
      "total_stock_quantity": 1987,
      "product_unit": {
        "id": 1,
        "name": "Ps",
        "symbol": "ps",
        "type": "quantity"
      },
      "notes": "",
      "latest_promotion_item": null,
      "category": {
        "id": 1,
        "name": "Fruits & Vegetables"
      },
      "brand": {
        "id": 1,
        "name": "Walmart"
      }
    },
    "related_items": {
      "data": [
        {
          "id": 2,
          "price": "22.95",
          "image": "products/1745483961_598300393_1.jpg",
          "image_url": "https://grozaar.heizoelscout.com/storage/products/1745483961_598300393_1.jpg",
          "name": "customer product",
          "barcode_image_url": "https://grozaar.heizoelscout.com/storage",
          "total_stock_quantity": 990,
          "taxes": {
            "has_tax": "1",
            "tax_amount": "1"
          },
          "rating": {
            "averageRating": "0",
            "totalReviewCount": 0
          }
        }
      ],
      "meta": {
        "current_page": 1,
        "from": 1,
        "last_page": 1,
        "per_page": 20,
        "to": 1,
        "total": 1
      },
      "links": {
        "first": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
        "last": "https://grozaar.heizoelscout.com/api/v1/user/get-product-details/1?page=1",
        "prev": null,
        "next": null
      }
    }
  }
}
*/

  bool? success;
  String? message;
  ProductDetailsResponseData? data;

  ProductDetailsResponse({this.success, this.message, this.data});

  ProductDetailsResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data =
        (json['data'] != null && (json['data'] is Map))
            ? ProductDetailsResponseData.fromJson(json['data'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
