///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class ProductResponseDataLinks {
  /*
{
  "first": "https://inventory.grozaarbd.com/api/v1/user/get-products?page=1",
  "last": "https://inventory.grozaarbd.com/api/v1/user/get-products?page=1",
  "prev": null,
  "next": null
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;

  ProductResponseDataLinks({this.first, this.last, this.prev, this.next});

  ProductResponseDataLinks.fromJson(Map<String, dynamic> json) {
    first = json['first']?.toString();
    last = json['last']?.toString();
    prev = json['prev']?.toString();
    next = json['next']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first'] = first;
    data['last'] = last;
    data['prev'] = prev;
    data['next'] = next;
    return data;
  }
}

class ProductResponseDataMeta {
  /*
{
  "current_page": 1,
  "from": 1,
  "last_page": 1,
  "per_page": 20,
  "to": 20,
  "total": 20
}
*/

  String? currentPage;
  String? from;
  String? lastPage;
  String? perPage;
  String? to;
  String? total;

  ProductResponseDataMeta({
    this.currentPage,
    this.from,
    this.lastPage,
    this.perPage,
    this.to,
    this.total,
  });

  ProductResponseDataMeta.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toString();
    from = json['from']?.toString();
    lastPage = json['last_page']?.toString();
    perPage = json['per_page']?.toString();
    to = json['to']?.toString();
    total = json['total']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['per_page'] = perPage;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class ProductResponseDataDataProductMeta {
  /*
{
  "id": 35,
  "product_id": 35,
  "unit_value": "2",
  "notes": "Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.\r\n\r\n\r\nACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M",
  "description": "<p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-0\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.</p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-1\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\"></p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-2\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">ACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M</p>"
}
*/

  String? id;
  String? productId;
  String? unitValue;
  String? notes;
  String? description;

  ProductResponseDataDataProductMeta({
    this.id,
    this.productId,
    this.unitValue,
    this.notes,
    this.description,
  });

  ProductResponseDataDataProductMeta.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productId = json['product_id']?.toString();
    unitValue = json['unit_value']?.toString();
    notes = json['notes']?.toString();
    description = json['description']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_id'] = productId;
    data['unit_value'] = unitValue;
    data['notes'] = notes;
    data['description'] = description;
    return data;
  }
}

class ProductResponseDataDataProductUnit {
  /*
{
  "id": 2,
  "name": "Kg",
  "symbol": "kg",
  "type": "weight"
}
*/

  String? id;
  String? name;
  String? symbol;
  String? type;

  ProductResponseDataDataProductUnit({
    this.id,
    this.name,
    this.symbol,
    this.type,
  });

  ProductResponseDataDataProductUnit.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    symbol = json['symbol']?.toString();
    type = json['type']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['symbol'] = symbol;
    data['type'] = type;
    return data;
  }
}

class ProductResponseDataDataBrand {
  /*
{
  "id": 6,
  "name": "Whole Foods",
  "image": null,
  "image_url": "https://inventory.grozaarbd.com/images/default/default.png",
  "status": "active"
}
*/

  String? id;
  String? name;
  String? image;
  String? imageUrl;
  String? status;

  ProductResponseDataDataBrand({
    this.id,
    this.name,
    this.image,
    this.imageUrl,
    this.status,
  });

  ProductResponseDataDataBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    imageUrl = json['image_url']?.toString();
    status = json['status']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['image_url'] = imageUrl;
    data['status'] = status;
    return data;
  }
}

class ProductResponseDataDataCategory {
  /*
{
  "id": 1,
  "name": "Atta, Rice & Dal",
  "image": "categories/1748152339_1991847555_1.png",
  "image_url": "https://inventory.grozaarbd.com/storage/categories/1748152339_1991847555_1.png",
  "slug": "fruits-vegetables",
  "status": "active"
}
*/

  String? id;
  String? name;
  String? image;
  String? imageUrl;
  String? slug;
  String? status;

  ProductResponseDataDataCategory({
    this.id,
    this.name,
    this.image,
    this.imageUrl,
    this.slug,
    this.status,
  });

  ProductResponseDataDataCategory.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    imageUrl = json['image_url']?.toString();
    slug = json['slug']?.toString();
    status = json['status']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['image_url'] = imageUrl;
    data['slug'] = slug;
    data['status'] = status;
    return data;
  }
}

class ProductResponseDataDataRating {
  /*
{
  "averageRating": "0",
  "totalReviewCount": 0
}
*/

  String? averageRating;
  String? totalReviewCount;

  ProductResponseDataDataRating({this.averageRating, this.totalReviewCount});

  ProductResponseDataDataRating.fromJson(Map<String, dynamic> json) {
    averageRating = json['averageRating']?.toString();
    totalReviewCount = json['totalReviewCount']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['averageRating'] = averageRating;
    data['totalReviewCount'] = totalReviewCount;
    return data;
  }
}

class ProductResponseDataData {
  /*
{
  "id": 35,
  "price": "10.20",
  "tax_price": "0.00",
  "promotion_price": "0.00",
  "sub_total": "10.20",
  "image_url": "https://inventory.grozaarbd.com/storage/products/1748755063_1284772420_1.webp",
  "name": "ACI Pure White Flour (Maida One)",
  "total_stock_quantity": 1000,
  "available_for": "Both",
  "rating": {
    "averageRating": "0",
    "totalReviewCount": 0
  },
  "created_at": "1 week",
  "category": {
    "id": 1,
    "name": "Atta, Rice & Dal",
    "image": "categories/1748152339_1991847555_1.png",
    "image_url": "https://inventory.grozaarbd.com/storage/categories/1748152339_1991847555_1.png",
    "slug": "fruits-vegetables",
    "status": "active"
  },
  "brand": {
    "id": 6,
    "name": "Whole Foods",
    "image": null,
    "image_url": "https://inventory.grozaarbd.com/images/default/default.png",
    "status": "active"
  },
  "product_unit": {
    "id": 2,
    "name": "Kg",
    "symbol": "kg",
    "type": "weight"
  },
  "product_meta": {
    "id": 35,
    "product_id": 35,
    "unit_value": "2",
    "notes": "Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.\r\n\r\n\r\nACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M",
    "description": "<p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-0\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.</p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-1\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\"></p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-2\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">ACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M</p>"
  },
  "promotion_text": "",
  "old_price": ""
}
*/

  String? id;
  String? price;
  String? taxPrice;
  String? promotionPrice;
  String? subTotal;
  String? imageUrl;
  String? name;
  String? totalStockQuantity;
  String? availableFor;
  ProductResponseDataDataRating? rating;
  String? createdAt;
  ProductResponseDataDataCategory? category;
  ProductResponseDataDataBrand? brand;
  ProductResponseDataDataProductUnit? productUnit;
  ProductResponseDataDataProductMeta? productMeta;
  String? promotionText;
  String? oldPrice;

  ProductResponseDataData({
    this.id,
    this.price,
    this.taxPrice,
    this.promotionPrice,
    this.subTotal,
    this.imageUrl,
    this.name,
    this.totalStockQuantity,
    this.availableFor,
    this.rating,
    this.createdAt,
    this.category,
    this.brand,
    this.productUnit,
    this.productMeta,
    this.promotionText,
    this.oldPrice,
  });

  ProductResponseDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    price = json['price']?.toString();
    taxPrice = json['tax_price']?.toString();
    promotionPrice = json['promotion_price']?.toString();
    subTotal = json['sub_total']?.toString();
    imageUrl = json['image_url']?.toString();
    name = json['name']?.toString();
    totalStockQuantity = json['total_stock_quantity']?.toString();
    availableFor = json['available_for']?.toString();
    rating =
        (json['rating'] != null && (json['rating'] is Map))
            ? ProductResponseDataDataRating.fromJson(json['rating'])
            : null;
    createdAt = json['created_at']?.toString();
    category =
        (json['category'] != null && (json['category'] is Map))
            ? ProductResponseDataDataCategory.fromJson(json['category'])
            : null;
    brand =
        (json['brand'] != null && (json['brand'] is Map))
            ? ProductResponseDataDataBrand.fromJson(json['brand'])
            : null;
    productUnit =
        (json['product_unit'] != null && (json['product_unit'] is Map))
            ? ProductResponseDataDataProductUnit.fromJson(json['product_unit'])
            : null;
    productMeta =
        (json['product_meta'] != null && (json['product_meta'] is Map))
            ? ProductResponseDataDataProductMeta.fromJson(json['product_meta'])
            : null;
    promotionText = json['promotion_text']?.toString();
    oldPrice = json['old_price']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['price'] = price;
    data['tax_price'] = taxPrice;
    data['promotion_price'] = promotionPrice;
    data['sub_total'] = subTotal;
    data['image_url'] = imageUrl;
    data['name'] = name;
    data['total_stock_quantity'] = totalStockQuantity;
    data['available_for'] = availableFor;
    if (rating != null) {
      data['rating'] = rating!.toJson();
    }
    data['created_at'] = createdAt;
    if (category != null) {
      data['category'] = category!.toJson();
    }
    if (brand != null) {
      data['brand'] = brand!.toJson();
    }
    if (productUnit != null) {
      data['product_unit'] = productUnit!.toJson();
    }
    if (productMeta != null) {
      data['product_meta'] = productMeta!.toJson();
    }
    data['promotion_text'] = promotionText;
    data['old_price'] = oldPrice;
    return data;
  }
}

class ProductResponseData {
  /*
{
  "data": [
    {
      "id": 35,
      "price": "10.20",
      "tax_price": "0.00",
      "promotion_price": "0.00",
      "sub_total": "10.20",
      "image_url": "https://inventory.grozaarbd.com/storage/products/1748755063_1284772420_1.webp",
      "name": "ACI Pure White Flour (Maida One)",
      "total_stock_quantity": 1000,
      "available_for": "Both",
      "rating": {
        "averageRating": "0",
        "totalReviewCount": 0
      },
      "created_at": "1 week",
      "category": {
        "id": 1,
        "name": "Atta, Rice & Dal",
        "image": "categories/1748152339_1991847555_1.png",
        "image_url": "https://inventory.grozaarbd.com/storage/categories/1748152339_1991847555_1.png",
        "slug": "fruits-vegetables",
        "status": "active"
      },
      "brand": {
        "id": 6,
        "name": "Whole Foods",
        "image": null,
        "image_url": "https://inventory.grozaarbd.com/images/default/default.png",
        "status": "active"
      },
      "product_unit": {
        "id": 2,
        "name": "Kg",
        "symbol": "kg",
        "type": "weight"
      },
      "product_meta": {
        "id": 35,
        "product_id": 35,
        "unit_value": "2",
        "notes": "Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.\r\n\r\n\r\nACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M",
        "description": "<p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-0\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.</p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-1\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\"></p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-2\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">ACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M</p>"
      },
      "promotion_text": "",
      "old_price": ""
    }
  ],
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 1,
    "per_page": 20,
    "to": 20,
    "total": 20
  },
  "links": {
    "first": "https://inventory.grozaarbd.com/api/v1/user/get-products?page=1",
    "last": "https://inventory.grozaarbd.com/api/v1/user/get-products?page=1",
    "prev": null,
    "next": null
  }
}
*/

  List<ProductResponseDataData?>? data;
  ProductResponseDataMeta? meta;
  ProductResponseDataLinks? links;

  ProductResponseData({this.data, this.meta, this.links});

  ProductResponseData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <ProductResponseDataData>[];
      v.forEach((v) {
        arr0.add(ProductResponseDataData.fromJson(v));
      });
      this.data = arr0;
    }
    meta =
        (json['meta'] != null && (json['meta'] is Map))
            ? ProductResponseDataMeta.fromJson(json['meta'])
            : null;
    links =
        (json['links'] != null && (json['links'] is Map))
            ? ProductResponseDataLinks.fromJson(json['links'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}

class ProductResponse {
  /*
{
  "success": true,
  "message": "Success",
  "data": {
    "data": [
      {
        "id": 35,
        "price": "10.20",
        "tax_price": "0.00",
        "promotion_price": "0.00",
        "sub_total": "10.20",
        "image_url": "https://inventory.grozaarbd.com/storage/products/1748755063_1284772420_1.webp",
        "name": "ACI Pure White Flour (Maida One)",
        "total_stock_quantity": 1000,
        "available_for": "Both",
        "rating": {
          "averageRating": "0",
          "totalReviewCount": 0
        },
        "created_at": "1 week",
        "category": {
          "id": 1,
          "name": "Atta, Rice & Dal",
          "image": "categories/1748152339_1991847555_1.png",
          "image_url": "https://inventory.grozaarbd.com/storage/categories/1748152339_1991847555_1.png",
          "slug": "fruits-vegetables",
          "status": "active"
        },
        "brand": {
          "id": 6,
          "name": "Whole Foods",
          "image": null,
          "image_url": "https://inventory.grozaarbd.com/images/default/default.png",
          "status": "active"
        },
        "product_unit": {
          "id": 2,
          "name": "Kg",
          "symbol": "kg",
          "type": "weight"
        },
        "product_meta": {
          "id": 35,
          "product_id": 35,
          "unit_value": "2",
          "notes": "Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.\r\n\r\n\r\nACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M",
          "description": "<p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-0\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">Pure Maida is produced from the finest wheat using European technology, perfect for preparing healthy and nutritious food. During the production of ACI Pure Maida, the wheat goes through many automatic cleaning stages that remove all impurities.</p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-1\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\"></p><p data-reactid=\".1f01dvkc5e2.$6203.0.1.0.1.5.$line-2\" style=\"-webkit-tap-highlight-color: transparent; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; color: rgb(190, 185, 179); font-family: &quot;Segoe UI&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, &quot;lucida grande&quot;, tahoma, verdana, arial, sans-serif; --darkreader-inline-color: var(--darkreader-text-beb9b3, #b2ada4);\" data-darkreader-inline-color=\"\">ACI Pure Maida is best for preparing Parata, Pizza, Samosa, and many more delicious items. ACI Pure M</p>"
        },
        "promotion_text": "",
        "old_price": ""
      }
    ],
    "meta": {
      "current_page": 1,
      "from": 1,
      "last_page": 1,
      "per_page": 20,
      "to": 20,
      "total": 20
    },
    "links": {
      "first": "https://inventory.grozaarbd.com/api/v1/user/get-products?page=1",
      "last": "https://inventory.grozaarbd.com/api/v1/user/get-products?page=1",
      "prev": null,
      "next": null
    }
  }
}
*/

  bool? success;
  String? message;
  ProductResponseData? data;

  ProductResponse({this.success, this.message, this.data});

  ProductResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data =
        (json['data'] != null && (json['data'] is Map))
            ? ProductResponseData.fromJson(json['data'])
            : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
